### ISSUE TITLE
Esc does not propagate

### ISSUE THREAD

**Issue by Prinzhorn** [pstanoev/simple-svelte-autocomplete#106]
Do you remember why you added this in the first commit https://github.com/pstanoev/simple-svelte-autocomplete/blame/master/src/SimpleAutocomplete.svelte#L738 ? I'm relying on events bubbling up.

**Comment by pstanoev** [comment]
Not sure... Do you have some idea what would be the consequence if that is removed?

**Comment by Prinzhorn** [comment]
> Do you have some idea what would be the consequence if that is removed?

In contrast to `preventDefault` this only affects other listeners for the same and none of the browser stuff. And you only have a single `on:keypress`, so it won't make any difference. I shouldn't affect `on:keypress` at all either.

**Comment by pstanoev** [comment]
Okay, I'll remove it in the next version.

**Comment by pstanoev** [comment]
Removed in version 2.2.4.
