### ISSUE TITLE
Is there a on:Focused event?

### ISSUE THREAD

**Issue by dydx-git** [pstanoev/simple-svelte-autocomplete#11]
How do I react to the component's focus event?

**Comment by Yahatix** [comment]
I would suggest to just expose the focus event on the input element like so:
```svelte
# SimpleAutocomplete.svelte
<input  
  on:focus
  on:focus={onFocus}
/>

# Implementation
<SimpleAutocomplete on:focus={()=>console.log('element has been focused')}/>
```

**Comment by fpassaniti** [comment]
a more generic approach would be to dispatch events from the internal input
to be able to deal with a wider range of scenario than just the focus event.

for now the workaround is to set an id through the id param, and then get it with a document.getElementById
that works but is not sveltic at all.

`<AutoComplete inputId={id} ...`

then 
```
onMount(() => {
        input = document.getElementById(id);
        input.autocomplete = 'off';
        input.addEventListener('focus', selectAll);
});

const selectAll = () => {
        input.select();
};
```

for example

**Comment by pstanoev** [comment]
`onFocus` and `onBlur` are added in version 2.1
