### ISSUE TITLE
Item selected, but not shown in dropdown

### ISSUE THREAD

**Issue by nika-d** [pstanoev/simple-svelte-autocomplete#115]
This issue is a correction of #112 . Sorry it was not clear enough the first time.

https://svelte.dev/repl/975dff31883e4cc99a2339703e5114b2?version=3.44.0 

The selectedItem is visible correctly in the input field, but the options list is not updated, causing a mismatch between selected and offered options. 

https://user-images.githubusercontent.com/46905562/138452368-c008c7a6-bb7a-4c4c-ac50-439ab08c197c.mov

There was a missunderstanding. @pstanoev wrote in #112:
"There are other components which filters the list to single item **after** selection."
-> But the filtering happens **before** the selection, according to the order of $: statements.

**Comment by pstanoev** [comment]
Fixed in version 2.2.4, thanks for the PR.
