### ISSUE TITLE
Dropdown scroll not working using key up/down

### ISSUE THREAD

**Issue by raratiru** [pstanoev/simple-svelte-autocomplete#118]
```
<script>
  import AutoComplete from "simple-svelte-autocomplete";

  const colorList = [
    { id: 1, name: "White", code: "#FFFFFF" },
    { id: 2, name: "Red", code: "#FF0000" },
    { id: 3, name: "Yellow", code: "#FF00FF" },
    { id: 4, name: "Green", code: "#00FF00" },
    { id: 5, name: "Blue", code: "#0000FF" },
    { id: 6, name: "Black", code: "#000000" },
    { id: 1, name: "White", code: "#FFFFFF" },
    { id: 2, name: "Red", code: "#FF0000" },
    { id: 3, name: "Yellow", code: "#FF00FF" },
    { id: 4, name: "Green", code: "#00FF00" },
    { id: 5, name: "Blue", code: "#0000FF" },
    { id: 6, name: "Black", code: "#000000" },
    { id: 7, name: "White", code: "#FFFFFF" },
    { id: 8, name: "Red", code: "#FF0000" },
    { id: 9, name: "Yellow", code: "#FF00FF" },
    { id: 10, name: "Green", code: "#00FF00" },
    { id: 11, name: "Blue", code: "#0000FF" },
    { id: 12, name: "Black", code: "#000000" },
    { id: 13, name: "White", code: "#FFFFFF" },
    { id: 14, name: "Red", code: "#FF0000" },
    { id: 15, name: "Yellow", code: "#FF00FF" },
    { id: 16, name: "Green", code: "#00FF00" },
    { id: 17, name: "Blue", code: "#0000FF" },
    { id: 18, name: "Black", code: "#000000" },
  ];

  let selectedColorObject;
</script>

<main>
  <form>
	<AutoComplete
	items={colorList}
	bind:selectedItem={selectedColorObject}
	labelFieldName="name" />
  </form>
</main>
```

The above code, results in a dropdown that will not scroll when using the keyboard to navigate the choices.

![dropdown](https://user-images.githubusercontent.com/6132160/139479785-356474c6-ff0f-4ae3-bfc4-a3f4b0c4692f.gif)

**Comment by pstanoev** [comment]
Firefox doesn't support scrollIntoViewIfNeeded() function which is used by the component.
https://developer.mozilla.org/en-US/docs/Web/API/Element/scrollIntoViewIfNeeded

This is so hard to fix properly.

**Comment by pstanoev** [comment]
This will likely never by supported by my component.
If somebody knows how to scroll an DOM element into view when the element is in a scrolling parent, please advise.

**Comment by raratiru** [comment]
OK, thank you for the answer. 

I am leaving this issue open should a workaround pops in.

**Comment by raratiru** [comment]
Thank you for the answer, indeed Firefox is the browser in question. 

I will stay tuned in case a workaround is posted.

**Comment by raratiru** [comment]
I found an article about [bootstrap dropdown](https://medium.com/@siddharthpandey_77104/svelte-bootstrap-drodown-component-d59c9cfbd349) and a [relevant REPL](https://svelte.dev/repl/f9b0e2f4193b4260b6b16bc097fa0155?version=3.23.0) where arrow down scrolls the dropdown in Firefox.
