### ISSUE TITLE
Using key for objects

### ISSUE THREAD

**Issue by avimar** [pstanoev/simple-svelte-autocomplete#12]
https://svelte.dev/repl/f88cf2ad315a419ea4e737e18b612a9e?version=3.23.2

I have an array of options.
I see the `valueFieldName` option to say which key to use as the value.

But when I bind to it with bind:value, it's not two-way -- when I change it elsewhere, it doesn't update locally. Also, when I initialize with a value, it seems to get overwritten.

Using `bind:selectedItem` works, but then I'm passing unnecessary nested data back and forth. I'm guessing that when I change a label name, the key won't match anymore either.

*Expected result*: when using `valueFieldName`, if the options are objects but the value is a string, it should find the option by the `valueFieldName`.

EDIT: to be clearer: when setting the value in the third box to one of the keys, I expect the autocomplete box to change.

**Comment by KatFrog** [comment]
I can look into this.

**Comment by pstanoev** [comment]
It may be not worth it since the binding works good if the `value` property is not used at all but the `selecteditem` is used.
The value derivation method is one way and changing value from outside won't change the selected item.
This can be tricky to fix and I am not sure that it needs fixing.
