### ISSUE TITLE
Sample code is broken

### ISSUE THREAD

**Issue by justingolden21** [pstanoev/simple-svelte-autocomplete#122]
Sample code (which has bad UX for selecting text) is:

```
<script>
const colors = ["White", "Red", "Yellow", "Green", "Blue", "Black", "Mät bläck", "<i>Jét Black</i>];
let selectedColor;
</script>

Selected color: {selectedColor}
<AutoComplete items={colors} bind:selectedItem={selectedColor} bind:highlightedItem={highlightedColor} />
```

From http://simple-svelte-autocomplete.surge.sh/

The last list item is missing a quote and `highlightedColor` is not defined.

This code also doesn't show how to import the package.

Thanks for looking into this.

**Comment by Wobbley** [comment]
It should be: `<AutoComplete items={colors} bind:selectedItem={selectedColor} />`

It's been fixed in the main branch a week ago, but perhaps not deployed yet.

**Comment by pstanoev** [comment]
Fixed.
