### ISSUE TITLE
Drop down shifts the entire page, not a popup.

### ISSUE THREAD

**Issue by avimar** [pstanoev/simple-svelte-autocomplete#13]
Expectation: The list of options is in the foreground, like a normal select box.
Seems to be working fine in the demo: http://simple-svelte-autocomplete.surge.sh/

But a simple repl shows it shifts all the elements below it: https://svelte.dev/repl/dd32e65146e543e6b3c2317f002c99f4?version=3.24.0

Ideas?
(I don't see any CSS in the repl compiled code, but I do in my dev version -- I guess that's only the local css, not the component css.)

**Comment by pstanoev** [comment]
Try this CSS:
	.autocomplete-list {
    background: #fff;
    position: relative;
    width: 100%;
    overflow-y: auto;
    z-index: 99;
    padding: 10px 0;
    top: 0px;
    border: 1px solid #999;
    max-height: calc(15 * (1rem + 10px) + 15px);
    user-select: none;
}

**Comment by avimar** [comment]
@pstanoev Can you modify the repl to make it work? Even as `:global(.autocomplete-list)` it didn't seem to have an affect.

But isn't this css part of the bundled component? Why isn't that working?

**Comment by pstanoev** [comment]
I don't know, probably has something to do with bulma.

If you used bulma as CSS framework it will likely work.

**Comment by michapixel** [comment]
.autocomplete-list {
		position: absolute;
		left: 0;
		top: 2rem; // adjust
		width: 100%;
		max-height: calc(6 * 1.8rem + 1rem) !important; // adjust
		padding: 0.2rem;// adjust
		
	}

**Comment by pstanoev** [comment]
Fixed with v1.2.0.
