### ISSUE TITLE
Support for required attribute?

### ISSUE THREAD

**Issue by timwis** [pstanoev/simple-svelte-autocomplete#133]
Hi there, thanks for this plugin! I was wondering if there's any way to mark the field as `required` so the form won't submit unless it has a value? I would think via the [`required` attribute](https://developer.mozilla.org/en-US/docs/Web/HTML/Element/input#attr-required) of the `<input>` or `<select>`

**Comment by PPP01** [comment]
I made a pull request for that:
https://github.com/pstanoev/simple-svelte-autocomplete/pull/137
