### ISSUE TITLE
Document breaking changes in v2

### ISSUE THREAD

**Issue by joelmukuthu** [pstanoev/simple-svelte-autocomplete#138]
Hi, thanks for this wonderful module! I'd like to upgrade from v1.3.2 to v2.2.4 but can't figure out what breaking changes were introduced in v2, even after skimming through the commits. Is it possible to document these?

**Comment by pstanoev** [comment]
Hi, unfortunately I have no time for that, please look a at the examples and try to adapt your code.
http://simple-svelte-autocomplete.surge.sh/

As I remember there were not too much breaking changes.
