### ISSUE TITLE
Allow custom properties for input (specifically id override) for accessibility

### ISSUE THREAD

**Issue by sdwvit** [pstanoev/simple-svelte-autocomplete#14]
Hello, thank you for component! It's almost perfect! 

I would like to request a feature that allows me to add Label with property 'for' attached to autocomplete's input for screenreaders.

Let me know how can I contribute

**Comment by pstanoev** [comment]
I am not sure how to do this.
Where would be the label?
Can you write sample code?
Or PR is welcomed as well.

**Comment by pstanoev** [comment]
Version v1.2.2 has option to specify id for the input field. Property is called `inputId`, see the homepage.

**Comment by zakaria-chahboun** [comment]
You can so that with passing 
```js
{...$$props}
```
 inside your component!
What here: https://youtu.be/G_W3k5Mlpig
