### ISSUE TITLE
on ajax search input case manipulation should be a setting

### ISSUE THREAD

**Issue by kemalkanok** [pstanoev/simple-svelte-autocomplete#151]
Hi there

https://github.com/pstanoev/simple-svelte-autocomplete/blob/5dc522d5f9e12b4add2d18ff4626c44ebe01140f/src/SimpleAutocomplete.svelte#L234

in that line its forcing to lower casing data that should be in settings

**Comment by kemalkanok** [comment]
https://github.com/pstanoev/simple-svelte-autocomplete/blob/5dc522d5f9e12b4add2d18ff4626c44ebe01140f/src/SimpleAutocomplete.svelte#L325

this kind of special characters removals are causing problems while searching with special characters this should be in settings too

**Comment by pstanoev** [comment]
`cleanUserText` can be set to false for the user entered text.
The keywords cleaning (result.toLowerCase().trim() ) will be in the next version:
`cleanKeywords` = false.
