### ISSUE TITLE
Whitespace sometimes causes infinite loop

### ISSUE THREAD

**Issue by Shkoklev** [pstanoev/simple-svelte-autocomplete#159]
When the option cleanUserText is set to false and the search function returns at least one item in the dropdown, if we try to append a whitespace character to the search term, an infinite loop is triggered and the component freezes
![Screenshot 2022-04-14 at 10 21 51](https://user-images.githubusercontent.com/37963788/163344633-d74727e0-8479-4690-8510-e88d00e9a01c.png)

The infinite loop is triggered in the highlightFilter function because the 'keywords' parameter contains an empty string as an element of the array.

**Comment by azmeuk** [comment]
Fixed by #160
