### ISSUE TITLE
Undefined className leads to "undefined" in HTML

### ISSUE THREAD

**Issue by paulschreiber** [pstanoev/simple-svelte-autocomplete#18]
Because `className` defaults to undefined, the literal string `undefined` appears in the markup, i.e.
```html
<div class="undefined autocomplete select is-fullwidth sautocomplete-763 svelte-gfsz5d">
```

Possible fixes:
* default className to `''`
* output an empty string if className is falsy  `<div class="{className || ''} autocomplete select is-fullwidth {uniqueId}">`

**Comment by pstanoev** [comment]
This should be fixed in the latest version:
class="{className ? className : ''}
