### ISSUE TITLE
Handle "overflow" better

### ISSUE THREAD

**Issue by martinjo** [pstanoev/simple-svelte-autocomplete#19]
When a selected item is takes up more space than is available it looks wierd.

![image](https://user-images.githubusercontent.com/1998726/95687907-c76bcd00-0c06-11eb-8334-83c9a6eeb4ea.png)

**Comment by pstanoev** [comment]
Hi @martinjo, as an alternative you can hide the blue arrow completely and replace it with custom implementation.
But will look into this to see what can be done.

**Comment by pstanoev** [comment]
Fixed in version 1.2.4.
