### ISSUE TITLE
Some small potential improvements & issues

### ISSUE THREAD

**Issue by seeekr** [pstanoev/simple-svelte-autocomplete#24]
Hey, first off thanks a lot for resurrecting the old svelte 2.x autocomplete and bringing it into the svelte 3.x world. I usually have pretty good google-fu, but I almost gave up in finding a good, but simple and easy to use autocomplete solution for a svelte 3.x app I'm developing, would have even been happy to use some non-bloated non-svelte version.

Anyway, I have a few suggestions for improvements to this library (and some minor issues, too) that I'd like to share, and hopefully someone (maybe even myself) will pick them up and do something productive with them!

- [ ] when I've already selected an item and click the autocomplete again, I may want to type something new now and would expect the autocomplete to select the text in there for me, so I can overwrite it without having to delete it first --> auto-select text contents when focused
- [ ] I don't necessarily want to keep displaying the text that has been entered or selected in the autocomplete field; sometimes I'd prefer to just show it as empty (ideally with an icon in there that signals "search/filter"), sometimes I'd want to just keep the text the user entered instead of changing the text to what ended up being selected
- [ ] when the autocomplete field is focused, I'd expect pressing ESC to clear its text contents (or revert to the previous selection / text if there was one and I started making changes, but then decided to abort midway through before making a new selection; but this part is already beyond what I really need / imagine at the moment)
- [ ] maybe the field could also provide an "X" icon on the right, to allow less keyboard-hotkey-savvy users to also easily clear the selection
- [ ] blue arrow overlapping text if text is long, making it non-recognizable and not user friendly when that happens

To provide a small bit of context about the use case here, in the current instance I'm using the component to control a multi-level (tree-style) navigation bar that allows direct jumping (to leaf nodes) instead of navigating via multiple clicks. So it's less of a form-field type usage and more of a persistent and repeatedly re-used search/filter/navigation element where "current state" is a lot less important (after selection) than the re-occurring event of typing/filtering and selection itself.

I'll leave this post as is for now, might get back to it later. I feel like some thinking about if any of this doesn't fit in with the simple "vision" for this component could be good, as well as considering how these might be implemented while keeping or even simplifying the API further. But brain doesn't want to do that right now, brain seems tired. :D

Cheers
Denis

**Comment by pstanoev** [comment]
Thanks for the thoughts @seeekr.

Some of the things I am aware and plan to include:
- X icon to clear the text
- ESC key support to clear (maybe)
- The overlapping of text and blue arrow

For the other usecases I will try to think of some event functions that you can use to achieve the described behavior.

Regards,
pstanoev

**Comment by pstanoev** [comment]
Some features implemented in version 1.2.4:

X icon to clear the text -> Implemented.
ESC key support to clear (maybe) -> there is already ESC key handling while the dropdown list is open. This is consistent with the regular <select> control. Additional functionality is not planned. 

The overlapping of text and blue arrow -> Fixed.
