### ISSUE TITLE
Logs warning when using search function

### ISSUE THREAD

**Issue by daniel17903** [pstanoev/simple-svelte-autocomplete#25]
When using the Autocomplete Component with a searchFunction this warning message appears in the browser console:
`SimpleAutocomplete.svelte:165 Autocomplete items / search function did not return array but undefined`

It appears even if the searchFunction never returns undefined and is also happening on the demo page http://simple-svelte-autocomplete.surge.sh/

**Comment by pstanoev** [comment]
Fixed in version 1.2.3.
