### ISSUE TITLE
Debounce in async result search?

### ISSUE THREAD

**Issue by the-yadu** [pstanoev/simple-svelte-autocomplete#30]
Is there a way to add debounce of lets say 250ms before it goes and hit the API?

**Comment by fpassaniti** [comment]
I don't find a way to achieve this also...
the searchFunction can't wait for the result... probably my poor JS skill..

It would be nice to propose an option for it

**Comment by fpassaniti** [comment]
If you want to update the lib directly,

simply replace onInput function by this :

```
    let delayedTimer;

    function onInput(e) {
        if (debug) {
            console.log("onInput");
        }

        if (delayedTimer) {
            clearTimeout(delayedTimer);
        }
        delayedTimer = setTimeout(() => {
            text = e.target.value;
            search();
            highlightIndex = 0;
            open();
        }, 200);
    }

```

It's hard coded to 200ms, but you get the concept, Ill maybe push a pull request if I have sometime later

**Comment by the-yadu** [comment]
You are amazing my friend. Thank you so much.
Also, If you want, I can raise a PR for this feature. 
I will just use your code above and make it as a prop to take denounce time.
Let me know if this sounds good.

**Comment by fpassaniti** [comment]
happy to help and contribute !
