### ISSUE TITLE
Attribute autocomplete on <input>

### ISSUE THREAD

**Issue by malgor** [pstanoev/simple-svelte-autocomplete#32]
Hi,

The browser's inbuilt autocomplete functionality is interfering with the simple-svelte-autocomplete list of matches.  There is a simple fix.  Add the attribute` autocomplete="off"` to the `<input>` element at around line 614.  See [MDN](https://developer.mozilla.org/en-US/docs/Web/Security/Securing_your_site/Turning_off_form_autocompletion) for more details.

BTW, this is a great component, very easy to use.

**Comment by azmeuk** [comment]
This issue is fixed by #35

**Comment by pstanoev** [comment]
Fixed in version 1.3.0
