### ISSUE TITLE
html on labelFunction also gets searched

### ISSUE THREAD

**Issue by mjgruta** [pstanoev/simple-svelte-autocomplete#37]
Below is my code.
`<AutoComplete 
items={countries} 
bind:selectedItem={selectedCountry} 
labelFunction={c => 
	'<a href="' + c.url + '"><span class="flag-icon ' + c.flag + '"> </span>' + c.name + '</a>'}
keywordsFunction={c => c.name}
/> 
`
When I type the letter "a" it seems to be searching all the HTML inside .autocomplete-list-item where I expect it to use the keywordsFunction to search for the keyword.
Is this an issue or I'm doing something wrong?

**Comment by pstanoev** [comment]
@mjgruta  checkout the new `slot` functionality in version 1.3.0 to customize the item. 
With this you will not need to supply labelFunction with HTML in it.
