### ISSUE TITLE
Asynchronous Submit Feature

### ISSUE THREAD

**Issue by jkmuka** [pstanoev/simple-svelte-autocomplete#39]
In this scenario, async calls are made to a server api which searches in cache. If no results are returned, does this component allow a submit event to the server via user pressing enter key or some button?

**Comment by pstanoev** [comment]
Seems like duplicate of #23 
For now we don't plan adding a feature to accept unlisted items.

**Comment by pstanoev** [comment]
Kind of supported in version 2.1. check the demo page, advances usage.
