### ISSUE TITLE
'value' seems to never be used

### ISSUE THREAD

**Issue by azmeuk** [pstanoev/simple-svelte-autocomplete#40]
The `value` variable is computed alongside the `text` variable when an item is selected.

https://github.com/pstanoev/simple-svelte-autocomplete/blob/e6a98524b86056aeea85dd041a75fa07d328e49a/src/SimpleAutocomplete.svelte#L141-L145

However, `value` is never read anywhere else in the code, nor bound to anything. I would have expected `value` to be bound to the `input` value attribute, but this is actually `text` that is:

https://github.com/pstanoev/simple-svelte-autocomplete/blob/e6a98524b86056aeea85dd041a75fa07d328e49a/src/SimpleAutocomplete.svelte#L733

When submitting the form, the input indeed holds the `text` value. This seems like a bug to me.
What do you think?

**Comment by pstanoev** [comment]
The value is exported property and it can be used, it is used in the demo:
```bind:value={selectedColorValue}``

It is a bit of unneeded property since you can always get the slectedItem and extract any value you need from it.
In favour of backward compatibility I won't consider removing it for now.
