### ISSUE TITLE
too much requests are generated

### ISSUE THREAD

**Issue by azmeuk** [pstanoev/simple-svelte-autocomplete#42]
If someone types a query very fast, say `lorem ipsum dolor`, a lot of network request will be generated (`l`, `lo`, `lor`, `lore`, `lorem`, `lorem `, `lorem i` ...). This causes several issues:

- the only useful query is `lorem ipsum dolor`
- ajax response may not come in the order they were sent, this leads to suggesting old queries while ignoring the current one. For instance the response for the `lor` query might come after `lorem ipsum dolor`, so the completion will be proposed for `lor` instead of `lorem ipsum dolor`.
- search queries might be slow on a server, sticking to the minimum useful queries might be a good idea

I can see several leads to fix this:

- Only send a request after there has been some inactivity on the field (i.e. wait a few milliseconds). That would probably go unnoticed by the end-user, but that may reduce the number of queries.
- Add a marker on each request, and expect the answer to have the same marker. This way the client side can know which request has been sent the last, and it can ignore old request coming too late. We can insipire on the [draw attribute](https://datatables.net/manual/server-side) on Datatables serverside processing mechanism. I suggest passing a `draw` parameter to the `searchFunction` that would be an increasing integer, and expect this same `draw` parameter to be returned by `searchFunction`. The [search](https://github.com/pstanoev/simple-svelte-autocomplete/blob/e6a98524b86056aeea85dd041a75fa07d328e49a/src/SimpleAutocomplete.svelte#L250) method would keep track of the highest `draw` values returned from `searchFunction` calls and would ignore all calls with a `draw` value below this.

What do you think?

**Comment by pstanoev** [comment]
`delay` parameter available in version 1.3.0.
