### ISSUE TITLE
Pass 'maxItemsToShowInList' to 'searchFunction'

### ISSUE THREAD

**Issue by azmeuk** [pstanoev/simple-svelte-autocomplete#48]
I suggest passing `maxItemsToShowInList` to the `searchFunction`.

This way the number of elements can be sent serverside, and would allow a server to only set the right number of elements in the response, and then save some bandwidth.

What do you think?

**Comment by pstanoev** [comment]
Since the feature shows "X elements not shown (but matching the input)" this number will be incorrect.
And this message will never be shown if the server limits the results.
The limit can still be done by not specifying maxItemsToShowInList and having the server return fixed set of results.

**Comment by azmeuk** [comment]
> Since the feature shows "X elements not shown (but Y matching the input)" this number will be incorrect.
And this message will never be shown if the server limits the results.

Maybe we could disable this feature on that kind of situations so we won't display false information? 
Another solution would be to allow the server to communicate the total amount of items with a kind of response like this:

```json
{
    "data": [.......],
    "nb_items_total": 9000
}
```

This is what datatables [serverside processing](https://datatables.net/manual/server-side#Returned-data) does.

>  The limit can still be done by not specifying maxItemsToShowInList and having the server return fixed set of results.

I would love something dynamical instead :)

**Comment by pstanoev** [comment]
The right approach is the server specifying data[] and totalNumberOfItems.
This is the common approach in many frameworks.

For this to be implemented generically, the search function that the component receives from "outside" needs to return object:

`result = {
  data: [] // real array of items
  count: 0 // the total number of items available 
}`

Then passing the `maxItemsToShowInList` to the `searchFunction` would make sense.

**Comment by azmeuk** [comment]
This is a neat solution indeed. Thee only thing that bother me with this is that, unlike lists, dicts are not compatible with [streamed responses](https://developer.mozilla.org/en-US/docs/Web/API/Streams_API/Using_readable_streams) (as illustrated in the *Async generator example*).

https://github.com/pstanoev/simple-svelte-autocomplete/blob/78d007c36f34d5d3762dcd76a60d6674bd3a6c16/src/SimpleAutocomplete.svelte#L396-L397

Another approach could be to still return a list, but the first item would be a *special* metadata item:
```
result = [
    {"count": 2}, // the metadata item
    {"foo": "bar"}, // the first real item
    {"foo": "baz"}, // the second real item
]
```
However this still feels wrong to me. What do you think?
