### ISSUE TITLE
Only display the arrow when list items are available

### ISSUE THREAD

**Issue by azmeuk** [pstanoev/simple-svelte-autocomplete#49]
The right arrow is always displayed, even when no data is available. This might be confusing for end-users.

![Screenshot_2021-04-09 Svelte Simple Autocomplete Demo](https://user-images.githubusercontent.com/60163/114192724-1bedcc00-994e-11eb-828f-976af1922fc5.png)

I suggest hiding the arrow when no data is available, or at least *grey* it does not call for a user action.

What do you think?

**Comment by pstanoev** [comment]
The component was done mostly for the case with local items.
The complete asynchronous support is kind of a bolt-on.
The arrow for example shows the dropdown with the last items from the search function which might be confusing.

The arrow can be hidden completely with `hideArrow` which might make more sense for server results.

But if it is usefull, I agree that one adding one more condition to not show the arrow when items is [] makes sense.
