### ISSUE TITLE
Reduce duplicate the labels

### ISSUE THREAD

**Issue by Metis77** [pstanoev/simple-svelte-autocomplete#5]
I am using this plugin to filter products and categories.
For the label I use the categories.

In the select dropdow there are as many categories as there are products. So there are plenty duplicate categories shown.

is it possible to reduce the dropdown categories?
`labelFunction={item => item.category}`
maybe like
`labelFunction={new Set(item => item.category)}`

**Comment by pstanoev** [comment]
Hi @Metis77,

This can be achieved by feeding the components just set of categories and not the list of products.
Otherwise what will be the item selected if if the label function only shows unique categories?

**Comment by pstanoev** [comment]
Hi @Metis77,

This can be achieved by feeding the components just set of categories and not the list of products.
Otherwise what will be the item selected if if the label function only shows unique categories?
