### ISSUE TITLE
When having two Autocomplete boxes on the same page, both stay open

### ISSUE THREAD

**Issue by six7** [pstanoev/simple-svelte-autocomplete#6]
First of all thanks for your work! Was easy to setup and implement!

I have the following problem: If I have two Autocomplete elements on one page and the user clicks from one open to the next - both stay open. Only a click outside of the Autocomplete triggers a close it seems, not a click to another one.

Is there any way to close an Autocomplete programmatically? Or perhaps my use case would be better solved if a click into another Autocomplete would trigger a close itself.

![SMA240wyer](https://user-images.githubusercontent.com/4548309/77834783-73f0d080-7147-11ea-898a-8c88694f519a.gif)

**Comment by pstanoev** [comment]
Thanks for reporting. Fixed locally will be published soon in a new version.

**Comment by pstanoev** [comment]
Fixed in commit: https://github.com/pstanoev/simple-svelte-autocomplete/commit/378563199c7e0bd11826a31877111f479d200ba6

Please update to version 1.1.2.
