### ISSUE TITLE
Dispatch to Parent Component

### ISSUE THREAD

**Issue by ejeme** [pstanoev/simple-svelte-autocomplete#7]
I can't seem to dispatch events from the Autocomplete component to a  Parent component in Svelte.  The binding works perfectly,  however, I need to be able to use a function which does not seem to work.

function change(event){
    ticker = "change"
    data = event.target.value
}

{#if ticker === "overview"}
    <AutoComplete bind:selectedValue **on:change={change}** />
{#if ticker === "change"}    
    <section>
    <Item 
        id={data}  />
</section>

**Comment by vfilatov** [comment]
try this:
 <AutoComplete bind:selectedValue **onChange**={change} />

**Comment by pstanoev** [comment]
onChange instead of on:change.
<AutoComplete bind:selectedValue **onChange**={change} />
