### ISSUE TITLE
`searchFunction` waiting on a result isn't "reacty"

### ISSUE THREAD

**Issue by mattfysh** [pstanoev/simple-svelte-autocomplete#86]
Should the library fire `searchFunction` and wait for a result? I thought the way to do things in Svelte's flavour of reactive programming is to fire functions off into the void, then just render whatever updates are made to a store.

So instead of this:

```js
async searchFunction = async () => {
  return await getTheThings()
}

<AutoComplete {searchFunction} ... >
```

You'd have something more like this:

```js
async searchFunction = async () => {
  $items = await getTheThings()
}

<AutoComplete items={$items} {searchFunction} ... >
```

**Comment by pstanoev** [comment]
Won't be supported by this component.
The component currently also takes care if the search function is executed multiple times and discards the results which are not received in order.
If it is done the proposed "Svelte way" you will need to handle that case as well.
If full control is needed, the proposition by @Prinzhorn is the way to go.
