### ISSUE TITLE
How to use onChange in this case?

### ISSUE THREAD

**Issue by frederikhors** [pstanoev/simple-svelte-autocomplete#90]
I created this REPL: https://svelte.dev/repl/bc15175d54cf4848a16a01bca8072f05?version=3.42.1 to understand how to handle this case.

As you can see I have an object with a property I don't want to change when I change other props with Select, hence I'm using `onChange()` with a `bind:selectedItem={value}` but as you can see this isn't working.

**If I remove the `bind:selectedItem` using `selectedItem={value}` it freezes my browser!**

Why?

**Comment by pstanoev** [comment]
The component changes the selectedItem from the list of available items, by referencing one of the items.
What you try to achieve with this code is not supported.
It can however be achieved by using 2 different variables, one for the selection from the autocomplete (where the doNotChangeThis will be removed) and one for the actual player with the doNotChangeThis property.
Lookup will have to be implemented in this case which links the selection form the Autocomplete from the one with the extended properties.

**Comment by frederikhors** [comment]
Can you write an example editing mine, please? I do not understand.

Plus maybe we can create an examples dir.

**Comment by pstanoev** [comment]
Here you go:
https://svelte.dev/repl/ffddc86ae79b47daa2f74781290968c6?version=3.42.1

**Comment by pstanoev** [comment]
Here you go:
https://svelte.dev/repl/6061886b6ff54f28a0a6b6eee4f14a9f?version=3.42.1
