### ISSUE TITLE
Words can be highlighted twice

### ISSUE THREAD

**Issue by azmeuk** [pstanoev/simple-svelte-autocomplete#96]
Say we have this query `foo foobar` and and item with name `foo foobar`. The item will be correctly matched, but the `foo` in `foobar` will be highlighted twice. This generates `<b>foo</b> <b><b>foo</b>bar</b>`

**Comment by pstanoev** [comment]
Should be fixed in 2.2.1.
I reworked the highlighting completely.
Not perfect but it avoids the big accent code.
https://svelte.dev/repl/42afa9f983464180947f2ed3387bf9df?version=3.42.3

**Comment by azmeuk** [comment]
Great! Thank you
